sudo: false
dist: trusty

language: php

php:
    - 5.3
    - 5.4
    - 5.5
    - 5.6
    - 7.0
    - 7.1

matrix:
  include:
    - php: 5.3
      dist: precise
    - php: 5.4
    - php: 5.5
    - php: 5.6
    - php: 7.0
    - php: 7.1

before_script:
  - php -m
  - php --info | grep -i 'intl\|icu\|pcre'

script: phpunit --debug

notifications:
    email:
        on_success: never
